### ISSUE TITLE
Authenticated user broken

### ISSUE THREAD

**Issue by gnumdk** [pylast/pylast#132]
```python
>>> u=network.get_authenticated_user()
>>> u.get_id()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/gnumdk/Téléchargements/pylast-1.2.1/pylast/__init__.py", line 3435, in get_id
    doc = self._request(self.ws_prefix + ".getInfo", True)
  File "/home/gnumdk/Téléchargements/pylast-1.2.1/pylast/__init__.py", line 1306, in _request
    params = self._get_params()
  File "/home/gnumdk/Téléchargements/pylast-1.2.1/pylast/__init__.py", line 3671, in _get_params
    return {"user": self.get_name()}
  File "/home/gnumdk/Téléchargements/pylast-1.2.1/pylast/__init__.py", line 3676, in get_name
    doc = self._request("user.getInfo", True, {"user": ""})    # hack
  File "/home/gnumdk/Téléchargements/pylast-1.2.1/pylast/__init__.py", line 1308, in _request
    return _Request(self.network, method_name, params).execute(cacheable)
  File "/home/gnumdk/Téléchargements/pylast-1.2.1/pylast/__init__.py", line 1136, in execute
    response = self._download_response()
  File "/home/gnumdk/Téléchargements/pylast-1.2.1/pylast/__init__.py", line 1127, in _download_response
    self._check_response_for_errors(response_text)
  File "/home/gnumdk/Téléchargements/pylast-1.2.1/pylast/__init__.py", line 1154, in _check_response_for_errors
    raise WSError(self.network, status, details)
pylast.WSError: No user with that name was found
```
I'm authenticated as scrobbling works...

**Comment by hugovk** [comment]
Strange, I get this:
```
>>> pylast.__version__
1.1.0
>>> u=network.get_authenticated_user()
>>> u.get_id()
u'1051899'
```

**Comment by hugovk** [comment]
Something to check: in `_download_response` in `pylast/__init__.py`, print out `data` and `response_text` to see what parameters are sent and what comes back.

Removing keys, I get:
`data`: `sk=SNIP&api_sig=SNIP&api_key=SNIP&user=hvk&method=user.getInfo`

`response_text`:
```xml
u'<?xml version="1.0" encoding="utf-8"?>
<lfm status="ok">
<user>
    <name>hvk</name>
    <realname></realname>
    <image size="small"></image>
    <image size="medium"></image>
    <image size="large"></image>
    <image size="extralarge"></image>
    <url>http://www.last.fm/user/hvk</url>
	<id>1051899</id>
	<lang>en</lang>
    <country></country>
    <age></age>
    <gender>n</gender>
    <subscriber>1</subscriber>
    <playcount>62709</playcount>
    <playlists>9</playlists>
    <bootstrap>0</bootstrap>
    <registered unixtime="1081980493">2004-04-15 00:08</registered>
	<type>subscriber</type>
</user></lfm>'
```

I get the same if I paste the parameter string at the end of http://ws.audioscrobbler.com/2.0/?

I created `network` like:

```python
network = pylast.LastFMNetwork(
    api_key=API_KEY, api_secret=API_SECRET,
    username=lastfm_username, password_hash=lastfm_password_hash)
```

What do you get?

**Comment by gnumdk** [comment]
gnumdk@debian:~$ python3
Python 3.4.3+ (default, May  7 2015, 23:10:14) 
[GCC 4.9.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pylast
>>> API_KEY = "7a9619a850ccf7377c46cf233c51e3c6"
>>> network = pylast.LastFMNetwork(api_key = API_KEY, username='lollypop_gnome', password_hash=pylast.md5("password"))
>>> u=network.get_authenticated_user()
>>> u.get_id()
<?xml version="1.0" encoding="utf-8"?>
<lfm status="failed">
<error code="6">
    No user with that name was found
</error>
</lfm>
 method=user.getInfo&user=&api_key=7a9619a850ccf7377c46cf233c51e3c6
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pylast.py", line 3410, in get_id
    doc = self._request(self.ws_prefix + ".getInfo", True)
  File "/usr/lib/python3/dist-packages/pylast.py", line 1305, in _request
    params = self._get_params()
  File "/usr/lib/python3/dist-packages/pylast.py", line 3646, in _get_params
    return {"user": self.get_name()}
  File "/usr/lib/python3/dist-packages/pylast.py", line 3651, in get_name
    doc = self._request("user.getInfo", True, {"user": ""})    # hack
  File "/usr/lib/python3/dist-packages/pylast.py", line 1307, in _request
    return _Request(self.network, method_name, params).execute(cacheable)
  File "/usr/lib/python3/dist-packages/pylast.py", line 1135, in execute
    response = self._download_response()
  File "/usr/lib/python3/dist-packages/pylast.py", line 1126, in _download_response
    self._check_response_for_errors(response_text)
  File "/usr/lib/python3/dist-packages/pylast.py", line 1153, in _check_response_for_errors
    raise WSError(self.network, status, details)
pylast.WSError: No user with that name was found

**Comment by hugovk** [comment]
Thanks. So you're not using an API secret when creating the `network`. I can reproduce it if I remove `api_secret`:

```python
network = pylast.LastFMNetwork(
    api_key=API_KEY, 
    username=lastfm_username, password_hash=lastfm_password_hash)
```

But this works:

```python
network = pylast.LastFMNetwork(
    api_key=API_KEY, api_secret=API_SECRET,
    username=lastfm_username, password_hash=lastfm_password_hash)
```

Please can you try with your API secret? Find it here: http://www.last.fm/api/accounts

**Comment by gnumdk** [comment]
Can i put the secret key in my software? Why it is called secret?

**Comment by hugovk** [comment]
Good to hear it works.

It's generally best to leave the secret (and key, but especially secret) out of software, especially open source software. Load them in from config files or environment variables, or import another Python file that just has those constants in them.

Someone with access to the key and secret can make another app using them, and if users have authorised your app to do stuff with their account, then someone else could also do nasty stuff to their accounts.

**Comment by gnumdk** [comment]
As soon i add secret key, scrobbler fails ...

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/pylast.py", line 4345, in scrobble
    "s": self._get_session_id(),
  File "/usr/lib/python3/dist-packages/pylast.py", line 4285, in _get_session_id
    self._do_handshake()
  File "/usr/lib/python3/dist-packages/pylast.py", line 4272, in _do_handshake
    server, params, self.network, "GET").execute().split("\n")
  File "/usr/lib/python3/dist-packages/pylast.py", line 4205, in execute
    self._check_response_for_errors(response)
  File "/usr/lib/python3/dist-packages/pylast.py", line 4223, in _check_response_for_errors
    raise BadAuthenticationError()
pylast.BadAuthenticationError: Bad authentication token

**Comment by gnumdk** [comment]
BADAUTH
 sk=6612a4810c12853030b3637943178985&p=1.2.1&t=1432567980&hs=true&c=tst&a=94cf0df5512fe576afb397bcc2fc8230&u=lollypop_gnome&v=1.0&api_key=SNIP

**Comment by gnumdk** [comment]
Ok, it works with network.scrobble  ...

**Comment by hugovk** [comment]
Good to hear! 

Some of my pylast-powered tools are here, you can check for examples: https://github.com/hugovk/lastfm-tools

And also the tests are basically example code too: https://github.com/pylast/pylast/blob/develop/tests/test_pylast.py
