### ISSUE TITLE
user.get_recent_tracks: AttributeError: Text instance has no attribute 'hasAttribute'

### ISSUE THREAD

**Issue by hugovk** [pylast/pylast#141]
Minimal example:

```
pip install pylast
```

```python
import pylast

API_KEY = TODO_ENTER_YOURS

network = pylast.LastFMNetwork(API_KEY)
user = network.get_user("RJ")

tracks = user.get_recent_tracks()
```

Exception:

```
C:\>python test.py
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    tracks = user.get_recent_tracks()
  File "C:\Python27\lib\site-packages\pylast\__init__.py", line 3427, in get_recent_tracks
    params):
  File "C:\Python27\lib\site-packages\pylast\__init__.py", line 4035, in _collect_nodes
    if main.hasAttribute("totalPages"):
AttributeError: Text instance has no attribute 'hasAttribute'
```

The examples at http://www.last.fm/api/show/user.getRecentTracks look fine, but this was working a week ago and is probably caused by the broken Last.fm API when they released the new site.

https://getsatisfaction.com/lastfm/topics/new-site-launch-temporary-service-disruption-information

**Comment by dharmaturtle** [comment]
Even if a user is currently listening to a song according to the front end, the API doesn't reflect this. A user's songs never have this attribute:

nowplaying="true"

http://ws.audioscrobbler.com/2.0/?method=user.getrecenttracks&user=anyuserhere&api_key=yourkeyhere

**Comment by hugovk** [comment]
@dharmaturtle Yes, lots of things have broken in the Last.fm API: typos, bad formats, broken XML, XML instead of JSON, missing attributes...

The missing nowplaying has been reported to Last.fm: https://getsatisfaction.com/lastfm/topics/api-known-issues?topic-reply-list%5Bsettings%5D%5Bfilter_by%5D=all&topic-reply-list%5Bsettings%5D%5Breply_id%5D=16021759#reply_16021759

**Comment by hugovk** [comment]
`_collect_nodes()` contains the line:
```python
        main = doc.documentElement.childNodes[1]
```

However, `doc.documentElement.childNodes` looks like this:
```
[<DOM Element: recenttracks at 0x10ba9e9e0>, <DOM Text node "u'\n'">]
```

Whatever used to be in index [1] is clearly not what we want now. Changing that `[1]` to `[0]` fixes the minimal example above.

---

Here's some output from the live API via http://www.last.fm/api/show/user.getRecentTracks:
```xml
<lfm status="ok">
<recenttracks user="RJ" page="1" perPage="1" totalPages="113533" total="113533">
<track>
<artist mbid="9a709693-b4f8-4da9-8cc1-038c911a61be">Bonobo</artist>
<name>The Keeper - Banks Remix</name>
<streamable>0</streamable>
<mbid/>
<album mbid="9f88f175-e5a3-4ffc-b80d-9be127f2f33c">Black Sands Remixed</album>
<url>
http://www.last.fm/music/Bonobo/_/The+Keeper+-+Banks+Remix
</url>
<image size="small">
http://img2-ak.lst.fm/i/u/34s/e6ccdabbbb51407398a426617304bc5b.png
</image>
<image size="medium">
http://img2-ak.lst.fm/i/u/64s/e6ccdabbbb51407398a426617304bc5b.png
</image>
<image size="large">
http://img2-ak.lst.fm/i/u/174s/e6ccdabbbb51407398a426617304bc5b.png
</image>
<image size="extralarge">
http://img2-ak.lst.fm/i/u/300x300/e6ccdabbbb51407398a426617304bc5b.png
</image>
<date uts="1441125269">01 Sep 2015, 16:34</date>
</track>
</recenttracks>
</lfm>
```

Here's some old XML from 2010 via https://forums.adobe.com/thread/558307?tstart=0:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<lfm status="ok">
 
<recenttracks user="RJ" page="1" perPage="2" totalPages="15332">
    <track> 
        <artist mbid="">Florence + The Machine</artist>
        <name>You've got the Love</name>
        <streamable>1</streamable>
        <mbid/>
        <album mbid="">Lungs</album>
        <url>http://www.last.fm/music/Florence%2B%252B%2BThe%2BMachine/_/Cosmic+Love</url>
        <image size="small">http://userserve-ak.last.fm/serve/34s/39934999.png</image>
        <image size="extralarge">http://userserve-ak.last.fm/serve/300x300/39934999.png</image>
        <date uts="1263401665">13 Jan 2010, 16:54</date>
    </track>
    
</recenttracks>
 
</lfm>
```

There's the problem. The API used to include encoding on the first line: 
```xml
<?xml version="1.0" encoding="UTF-8"?>
```

**Comment by hugovk** [comment]
But of course that change break Libre.fm.

```
import pylast

API_KEY = "1"

# network = pylast.LastFMNetwork(API_KEY)
network = pylast.LibreFMNetwork(API_KEY)
user = network.get_user("RJ")

tracks = user.get_recent_tracks()
# print(tracks)
```

For Libre.fm, `doc.documentElement.childNodes` looks like this:
```
[<DOM Text node "u'\n  '">, <DOM Element: recenttracks at 0x24cf548>, <DOM Text node "u'\n'">]
```

A more robust fix is needed.
