### ISSUE TITLE
Submitting information to Libre.fm not possible

### ISSUE THREAD

**Issue by 0nse** [pylast/pylast#168]
I want to scrobble to Libre.fm and update the now playing status.

```python
network = LibreFMNetwork(username='my_user_name',
                         password_hash=md5('my_password'))
```
This does not throw an error.

Using `network.update_now_playing()` or `network.scrobble()` with the same parameters I successfully use for Last.fm-scrobbling, I will get the following error:
```python
WARNING  Error submitting playing track to Libre.fm: {'status': u'6', 'details': u'Invalid parameters - Your request is missing a required parameter', 'network': pylast.LibreFMNetwork('', '', '', 'my_user_name', 'my_password_hash')}
```

Inspecting the `network` object, I see that it is missing a session key (the Last.fm network is not), which to my knowledge should actually be automatically generated given `username` and `password_hash`.
```python
WARNING  {'username': u'my_user_name', 'cache_backend': None, 'session_key': '', 'name': 'Libre.fm', 'api_secret': '', 'domain_names': {0: 'alpha.libre.fm', 1: 'alpha.libre.fm', 2: 'alpha.libre.fm', 3: 'alpha.libre.fm', 4: 'alpha.libre.fm', 5: 'alpha.libre.fm', 6: 'alpha.libre.fm', 7: 'alpha.libre.fm', 8: 'alpha.libre.fm', 9: 'alpha.libre.fm', 10: 'alpha.libre.fm', 11: 'alpha.libre.fm'}, 'proxy_enabled': False, 'submission_server': 'http://turtle.libre.fm:80/', 'proxy': None, 'urls': {'album': 'artist/%(artist)s/album/%(album)s', 'playlist': 'user/%(user)s/library/playlists/%(appendix)s', 'tag': 'tag/%(name)s', 'group': 'group/%(name)s', 'user': 'user/%(name)s', 'artist': 'artist/%(artist)s', 'track': 'music/%(artist)s/_/%(title)s', 'country': 'place/%(country_name)s', 'event': 'event/%(id)s'}, 'last_call_time': 0, 'limit_rate': False, 'api_key': '', 'homepage': 'http://alpha.libre.fm', 'ws_server': ('alpha.libre.fm', '/2.0/'), 'password_hash': 'my_password_hash'}
```

Manually retrieving the session key fails.

```python
# my code:
SessionKeyGenerator(network.get_session_key(network.username, network.password_hash))

# the error:
ERROR    Triggering event failed: track_playback_started
Traceback (most recent call last):
[...]
  File "/usr/lib/python2.7/site-packages/pylast/__init__.py", line 1258, in get_session_key
    doc = request.execute()
  File "/usr/lib/python2.7/site-packages/pylast/__init__.py", line 1137, in execute
    response = self._download_response()
  File "/usr/lib/python2.7/site-packages/pylast/__init__.py", line 1128, in _download_response
    self._check_response_for_errors(response_text)
  File "/usr/lib/python2.7/site-packages/pylast/__init__.py", line 1157, in _check_response_for_errors
    raise WSError(self.network, status, details)
WSError: Invalid authentication token supplied
```

I see this behaviour when using pylast 1.4.2 as well as 1.5.1. Again, I want to stress that everything works perfectly fine with Last.fm. If it matters, my password is quite long (>60 chars) and contains several special characters.

**Comment by hugovk** [comment]
This works for me with Libre.fm, based on [bbcscrobbler](https://github.com/hugovk/bbcscrobbler/blob/master/bbcscrobbler.py#L215-L237) for Last.fm. If you've not done so, it asks you to authenticate via the browser, then saves the auth to a local file for next time:

```python
#!/usr/bin/env python
# encoding: utf-8

import pylast

import os
import time

LIBREFM_SESSION_KEY_FILE = os.path.join(os.path.expanduser("~"), ".session_key.librefm")


librefm = pylast.LibreFMNetwork(username='my_username',
                                password_hash=pylast.md5('my_password'))

def session(network, key_file):
    if not os.path.exists(key_file):
        skg = pylast.SessionKeyGenerator(network)
        url = skg.get_web_auth_url()

        print(
            "Please authorize the scrobbler "
            "to scrobble to your account: %s\n" % url)
        import webbrowser
        webbrowser.open(url)

        while True:
            try:
                session_key = skg.get_web_auth_session_key(url)
                fp = open(key_file, "w")
                fp.write(session_key)
                fp.close()
                break
            except pylast.WSError:
                time.sleep(1)
    else:
        session_key = open(key_file).read()

    network.session_key = session_key

session(librefm, LIBREFM_SESSION_KEY_FILE)

librefm.update_now_playing("Nirvana", "Lithium")
```

**Comment by 0nse** [comment]
That works, thank you very much! Is there an option to transmit a client name/URL?

![unknown](https://cloud.githubusercontent.com/assets/7449611/12947942/56e8ba18-cfff-11e5-8cf3-bf9c335591b1.png)

**Comment by hugovk** [comment]
You're welcome! 

I'm not so familiar with Libre.fm but I guess you'd need to register an application with Libre.fm and then use the API key and secret they give you. At least that's how Last.fm does it, and Libre.fm try to mirror that. See:

https://github.com/hugovk/bbcscrobbler/blob/master/bbcscrobbler.py#L215
