### ISSUE TITLE
Build: pypy3 failing

### ISSUE THREAD

**Issue by hugovk** [pylast/pylast#187]
```
Collecting pip
/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/virtualenv_support/pip-9.0.1-py2.py3-none-any.whl/pip/_vendor/pkg_resources/__init__.py:83: UserWarning: Support for Python 3.0-3.2 has been dropped. Future versions will fail here.
pip requires Python '>=2.6,!=3.0.*,!=3.1.*,!=3.2.*' but the running Python is 3.2.5
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/virtualenv.py", line 2328, in <module>
    main()
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/virtualenv.py", line 713, in main
    symlink=options.symlink)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/virtualenv.py", line 945, in create_environment
    download=download,
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/virtualenv.py", line 901, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/home/travis/virtualenv/python2.7.9/lib/python2.7/site-packages/virtualenv.py", line 797, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/travis/build/p....tox/pypy3/bin/pypy3 - setuptools pip wheel failed with error code 1
Running virtualenv with interpreter /opt/python/pypy3-2.4.0/bin/pypy3
ERROR: InvocationError: /home/travis/virtualenv/python2.7.9/bin/python -m virtualenv --python /opt/python/pypy3-2.4.0/bin/pypy3 pypy3 (see /home/travis/build/pylast/pylast/.tox/pypy3/log/pypy3-0.log)
___________________________________ summary ____________________________________
ERROR:   pypy3: InvocationError: /home/travis/virtualenv/python2.7.9/bin/python -m virtualenv --python /opt/python/pypy3-2.4.0/bin/pypy3 pypy3 (see /home/travis/build/pylast/pylast/.tox/pypy3/log/pypy3-0.log)
```
https://travis-ci.org/pylast/pylast/jobs/188239329

**Comment by hugovk** [comment]
PyPy3 has been updated on Travis CI and it's pasing on the last build:
https://travis-ci.org/pylast/pylast/builds/270983107
