### ISSUE TITLE
Can't get the artist name when using user.get_weekly_artist_charts()

### ISSUE THREAD

**Issue by Frenkieb** [pylast/pylast#257]
I'm trying to get the names of my top 3 artists of last week with user.get_weekly_artist_charts() but I run into an error or get I get None as a result and I don't see what I'm doing wrong. 

```python
import pylast

API_KEY = ""
API_SECRET = ""

username = ""
password_hash = pylast.md5("")

network = pylast.LastFMNetwork(api_key=API_KEY, api_secret=API_SECRET, username=username, password_hash=password_hash)

user = network.get_authenticated_user();

weekly_artists = user.get_weekly_artist_charts();

# Keep the first three artists.
del weekly_artists[3:]

# Print the artist name and number of songs(weight).
for weekly_artist in weekly_artists:
  artist,weight = weekly_artist

  print (artist.get_name())
  print (artist.get_correction())
```

artist.get_name() returns 

```
None
```
artist.get_correction() returns

```
Traceback (most recent call last):
  File "G:\projects\python\lastfm_weekly\lastfm-weekly.py", line 28, in <module>
    print (artist.get_correction())
  File "C:\Users\..\Python\Python36-32\lib\site-packages\pylast\__init__.py", line 1585, in get_correction
    self._request(self.ws_prefix + ".getCorrection"), "name")
  File "C:\Users\..\Python\Python36-32\lib\site-packages\pylast\__init__.py", line 1029, in _request
    return _Request(self.network, method_name, params).execute(cacheable)
  File "C:\Users\..\Python\Python36-32\lib\site-packages\pylast\__init__.py", line 744, in __init__
    network._get_ws_auth()
AttributeError: 'str' object has no attribute '_get_ws_auth'
```

What am I doing wrong?

See also StackOverflow: [https://stackoverflow.com/questions/49581125/get-artist-name](https://stackoverflow.com/questions/49581125/get-artist-name)

**Comment by hugovk** [comment]
What do you get when you print weekly artists before the del?

And after the del?

And when printing artist inside the loop?

**Comment by Frenkieb** [comment]
Before the del:

````
[TopItem(item=pylast.Artist(None, 'Primordial'), weight=30), TopItem(item=pylast.Artist(None, 'vojd'), weight=22), TopItem(item=pylast.Artist(None, 'Negative Self'), weight=21), TopItem(item=pylast.Artist(None, 'Monster Magnet'), weight=20), TopItem(item=pylast.Artist(None, 'Texas Hippie Coalition'), weight=20), TopItem(item=pylast.Artist(None, 'Arckanum'), weight=16), TopItem(item=pylast.Artist(None, 'Djevel'), weight=15), TopItem(item=pylast.Artist(None, 'Skeletal Remains'), weight=15), TopItem(item=pylast.Artist(None, 'NOFX'), weight=13), TopItem(item=pylast.Artist(None, 'Clandestine Blaze'), weight=12), TopItem(item=pylast.Artist(None, 'Death Alley'), weight=12), TopItem(item=pylast.Artist(None, 'Der Weg einer Freiheit'), weight=11), TopItem(item=pylast.Artist(None, 'Bloodhound Gang'), weight=10), TopItem(item=pylast.Artist(None, 'Necrophobic'), weight=10), TopItem(item=pylast.Artist(None, 'Tribulation'), weight=10), TopItem(item=pylast.Artist(None, 'Moonsorrow'), weight=9), TopItem(item=pylast.Artist(None, 'Ascension'), weight=8), TopItem(item=pylast.Artist(None, 'Burzum'), weight=8), TopItem(item=pylast.Artist(None, 'Angantyr'), weight=7), TopItem(item=pylast.Artist(None, 'Myrkraverk'), weight=6), TopItem(item=pylast.Artist(None, 'Enthroned'), weight=5), TopItem(item=pylast.Artist(None, 'Battle Axe'), weight=3), TopItem(item=pylast.Artist(None, 'Bon Jovi'), weight=3), TopItem(item=pylast.Artist(None, 'Mötley Crüe'), weight=3), TopItem(item=pylast.Artist(None, 'Quiet Riot'), weight=3), TopItem(item=pylast.Artist(None, 'Dio'), weight=2), TopItem(item=pylast.Artist(None, 'Kiss'), weight=2), TopItem(item=pylast.Artist(None, 'Ratt'), weight=2), TopItem(item=pylast.Artist(None, 'Scorpions'), weight=2), TopItem(item=pylast.Artist(None, 'Van Halen'), weight=2), TopItem(item=pylast.Artist(None, 'Whitesnake'), weight=2), TopItem(item=pylast.Artist(None, 'Alice Cooper'), weight=1), TopItem(item=pylast.Artist(None, 'Cinderella'), weight=1), TopItem(item=pylast.Artist(None, 'David Lee Roth'), weight=1), TopItem(item=pylast.Artist(None, 'Def Leppard'), weight=1), TopItem(item=pylast.Artist(None, 'Europe'), weight=1), TopItem(item=pylast.Artist(None, 'Great White'), weight=1), TopItem(item=pylast.Artist(None, "Guns N' Roses"), weight=1), TopItem(item=pylast.Artist(None, 'Harakiri for the Sky'), weight=1), TopItem(item=pylast.Artist(None, 'Iron Maiden'), weight=1), TopItem(item=pylast.Artist(None, 'Iron Reagan'), weight=1), TopItem(item=pylast.Artist(None, 'Lita Ford'), weight=1), TopItem(item=pylast.Artist(None, 'Motörhead'), weight=1), TopItem(item=pylast.Artist(None, 'Necrowretch'), weight=1), TopItem(item=pylast.Artist(None, 'Ozzy Osbourne'), weight=1), TopItem(item=pylast.Artist(None, 'Poison'), weight=1), TopItem(item=pylast.Artist(None, 'Power Trip'), weight=1), TopItem(item=pylast.Artist(None, 'Twisted Sister'), weight=1), TopItem(item=pylast.Artist(None, 'Winger'), weight=1)]
````

After the del:

```
[TopItem(item=pylast.Artist(None, 'Primordial'), weight=30), TopItem(item=pylast.Artist(None, 'vojd'), weight=22), TopItem(item=pylast.Artist(None, 'Negative Self'), weight=21)]
```

Artist inside the loop:

```
None
None
None
```

**Comment by hugovk** [comment]
Thanks! This is a bug in pylast, fixed in https://github.com/pylast/pylast/pull/258.

When building the charts from the response from Last.fm, it was using some common code for charts for artists, albums and tracks.

It was creating artist, album or track objects by passing it the `artist` and `name` (and network).

But that only makes sense for album and track. For artists, there is no `artist` field, the `name` is the artist's name.

**Comment by hugovk** [comment]
You're welcome, thank you for reporting it.

There'll be a new release in the next few weeks, in the meantime you can install directly from Git; see the README for how.

**Comment by hugovk** [comment]
pylast 2.2.0 is now released with the fix.
