### ISSUE TITLE
Unable to collect all tracks from user using `get_recent_tracks`

### ISSUE THREAD

**Issue by gomesfernanda** [pylast/pylast#296]
### What did you do?
Used the method `user.get_recent_tracks(limit=None, cacheable=True)` to collect all my scrobbles, from the beginning.

### What did you expect to happen?
To return all my scrobbles since I created my account, using **limit=None**.

### What actually happened?
I got the error 

```
Traceback (most recent call last):
  File "/Users/fernandagomes/dev/GitHub_repos/gomesfernanda/lastfm-reports/lastfm_functions.py", line 165, in <module>
    get_recent_tracks(user, network, limit=None)
  File "/Users/fernandagomes/dev/GitHub_repos/gomesfernanda/lastfm-reports/lastfm_functions.py", line 90, in get_recent_tracks
    recent_tracks = user.get_recent_tracks(limit=None, cacheable=True)
  File "/Users/fernandagomes/dev/GitHub_repos/gomesfernanda/lastfm-reports/lastenv/lib/python3.6/site-packages/pylast/__init__.py", line 2336, in get_recent_tracks
    limit, self, self.ws_prefix + ".getRecentTracks", cacheable, params
  File "/Users/fernandagomes/dev/GitHub_repos/gomesfernanda/lastfm-reports/lastenv/lib/python3.6/site-packages/pylast/__init__.py", line 2735, in _collect_nodes
    doc = sender._request(method_name, cacheable, params)
  File "/Users/fernandagomes/dev/GitHub_repos/gomesfernanda/lastfm-reports/lastenv/lib/python3.6/site-packages/pylast/__init__.py", line 1112, in _request
    return _Request(self.network, method_name, params).execute(cacheable)
  File "/Users/fernandagomes/dev/GitHub_repos/gomesfernanda/lastfm-reports/lastenv/lib/python3.6/site-packages/pylast/__init__.py", line 954, in execute
    response = self._download_response()
  File "/Users/fernandagomes/dev/GitHub_repos/gomesfernanda/lastfm-reports/lastenv/lib/python3.6/site-packages/pylast/__init__.py", line 943, in _download_response
    self._check_response_for_errors(response_text)
  File "/Users/fernandagomes/dev/GitHub_repos/gomesfernanda/lastfm-reports/lastenv/lib/python3.6/site-packages/pylast/__init__.py", line 973, in _check_response_for_errors
    raise WSError(self.network, status, details)
pylast.WSError: Operation failed - Most likely the backend service failed. Please try again.
```

I was able to run this script and collect all data from a user friend of mine because he had only ~2k scrobbles. However, I believe that for users with many scrobbles this fails.

### What versions of OS, Python and pylast are you using?
MacOS version: 10.14.2
Python version: Python 3.6.4
pylast version: 2.4.0

Please include **code** that reproduces the issue.

```python
def get_recent_tracks(user, network):
	# network is passed as a network = pylast.LastFMNetwork(api_key, api_secret, username, password_hash)
    recent_tracks_list = []
    user = network.get_user(user)
    recent_tracks = user.get_recent_tracks(limit=None, cacheable=True)
    for i, track in enumerate(recent_tracks):
        track_list = []
        track_list.append(track.track.artist.name)
        track_list.append(track.track.title)
        track_list.append(track.timestamp)
        recent_tracks_list.append(track_list)
    return recent_tracks_list
```

**Comment by hugovk** [comment]
Thanks for the report, I have nearly 100k scrobbles and can reproduce it as well.

Sometimes it will complete fine, but it's not unusual to get 1-3 "Operation failed - Most likely the backend service failed. Please try again." exceptions, or other network errors.

There's no point catching them outside pylast and retrying, as it needs to make all those calls again, and may fail somewhere in the middle.

I've created PR #297 to fix these, please can you check it?

---

For some debugging when testing, this shows any exceptions that happen, and some progress as it goes through the pages of results:

```diff
diff --git a/pylast/__init__.py b/pylast/__init__.py
index dc71cf5..3edaa22 100644
--- a/pylast/__init__.py
+++ b/pylast/__init__.py
@@ -2783,6 +2783,7 @@ def _collect_nodes(limit, sender, method_name, cacheable, params=None):
                 doc = sender._request(method_name, cacheable, params)
                 break  # success
             except Exception as e:
+                print(tries, e)
                 if tries >= 3:
                     raise e
                 # Wait and try again
@@ -2802,6 +2803,8 @@ def _collect_nodes(limit, sender, method_name, cacheable, params=None):
             total_pages = _number(main.getAttribute("totalpages"))
         else:
             raise Exception("No total pages attribute")
+        if page % 10 == 0:
+            print(page, total_pages)

         for node in main.childNodes:
             if not node.nodeType == xml.dom.Node.TEXT_NODE and (
```

**Comment by yoomy3** [comment]
+1 on this issue. I am trying to get 90k scrobbles, but the call keeps failing. Any idea on when this issue will be resolved?

**Comment by hugovk** [comment]
I've created PR #297 to fix these, please can you check it?

**Comment by yoomy3** [comment]
Hi @hugovk , I have not tested the changes that you made in PR #297 myself, but it looks good to me. It makes more sense for pylast to retry a couple of times before the entire function call fails, which would save lots of time from making all calls from the beginning.

**Comment by gomesfernanda** [comment]
Same goes for me, LGTM. Thanks!
