### ISSUE TITLE
Unable to scrobble any tracks using the scrobble method - pylast.MalformedResponseError

### ISSUE THREAD

**Issue by ryancambray** [pylast/pylast#373]
### What did you do?
`utils.network.scrobble(artist=artist, title=trackname, timestamp=timestamp)`

where the artist and title are strings and the timestamp variable is
`timestamp=int(time.time())`
### What did you expect to happen?
Scrobble the track with timestamp
### What actually happened?
```Traceback (most recent call last):
  File "/home/ryan/.local/share/virtualenvs/cambot-Cr-HoN4d/lib/python3.9/site-packages/pylast/__init__.py", line 981, in _check_response_for_errors
    doc = minidom.parseString(_string(response).replace("opensearch:", ""))
  File "/usr/local/lib/python3.9/xml/dom/minidom.py", line 1998, in parseString
    return expatbuilder.parseString(string)
  File "/usr/local/lib/python3.9/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/local/lib/python3.9/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: syntax error: line 1, column 0
```

### What versions are you using?

* OS: WSL2 Ubuntu 20.04
* Python: 3.9.7
* pylast: 4.3.0

Please include **code** that reproduces the issue.

The [best reproductions](https://stackoverflow.com/help/minimal-reproducible-example)
are
[self-contained scripts](https://ericlippert.com/2014/03/05/how-to-debug-small-programs/)
with minimal dependencies.

```python
#!/usr/bin/env python
#  -*- coding: utf-8 -*-
import logging
import config
import cambot_utils as utils
import argparse
import datetime
import time
import sys

def check_syntax(track):
    if "-" not in track:
        logging.warn("Track - [{}] - cannot be scrobbled. Incorrect format".format(track))
        return
    track_split = track.split("-", maxsplit=1)
    artist = None
    trackname = None

    if reverse:
        artist = track_split[-1].strip()
        trackname = track_split[0].strip()
    else:
        trackname = track_split[-1].strip()
        artist = track_split[0].strip()

    timestamp=int(time.time())
    
    logging.info("Attempting to scrobble '{}'".format(track))
    logging.info("Artist: {}".format(artist))
    logging.info("Track: {}".format(trackname))
    logging.info("Timestamp: {}".format(timestamp))

    try:
        if not test:
            utils.network.scrobble(artist=artist, title=trackname, timestamp=timestamp)
    except utils.pylast.MalformedResponseError as e:
        logging.error("Unable to scrobble '{}'".format(track))
        logging.error(e)


parser = argparse.ArgumentParser()
parser.add_argument("--file", help="A text file that contains the songs you want to scrobble in '%Artist%' - '%Name%' format with each scrobble on a newline", required=True)
parser.add_argument("--reverse", help="If the tracklist is stored in the format of '%track% - %artist'", action="store_true")
parser.add_argument("--test", help="Testing. Do not scrobble", action="store_true")
args = parser.parse_args()

file = args.file
reverse = args.reverse
test = args.test

if reverse:
    logging.info("Treating track list in %track% - %artist% format")
if test:
    logging.info("Test mode. Will not scrobble")

with open(file) as tracklist:
    for track in tracklist:
        check_syntax(track)
```

**Comment by hugovk** [comment]
Please could you check with the previous release 4.2.1?

I don't think anything relevant changed, but 4.3.0 just came out so would be good to rule out.

**Comment by ryancambray** [comment]
No worries. I was on v4.2.1 before I tried 4.3.0 yesterday so I can say its the same error. This is the output with v4.2.1
```
(cambot) ryan@RhitonsPC:/mnt/d/repos/cambot$ pipenv run cambot/tracklist_scrobbler.py --file '/mnt/e/DJ vids/2021/summer/toptrackssummer2021.txt'
05-Oct-21 14:26:16 - tracklist_scrobbler - INFO - Attempting to scrobble 'Caribou - You Can Do It
'
05-Oct-21 14:26:16 - tracklist_scrobbler - INFO - Artist: Caribou
05-Oct-21 14:26:16 - tracklist_scrobbler - INFO - Track: You Can Do It
05-Oct-21 14:26:16 - tracklist_scrobbler - INFO - Timestamp: 1633440376
Traceback (most recent call last):
  File "/home/ryan/.local/share/virtualenvs/cambot-Cr-HoN4d/lib/python3.9/site-packages/pylast/__init__.py", line 981, in _check_response_for_errors
    doc = minidom.parseString(_string(response).replace("opensearch:", ""))
  File "/usr/local/lib/python3.9/xml/dom/minidom.py", line 1998, in parseString
    return expatbuilder.parseString(string)
  File "/usr/local/lib/python3.9/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
  File "/usr/local/lib/python3.9/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: syntax error: line 1, column 0

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/mnt/d/repos/cambot/cambot/tracklist_scrobbler.py", line 72, in <module>
    check_syntax(track)
  File "/mnt/d/repos/cambot/cambot/tracklist_scrobbler.py", line 35, in check_syntax
    utils.network.scrobble(artist=artist, title=trackname, timestamp=timestamp)
  File "/home/ryan/.local/share/virtualenvs/cambot-Cr-HoN4d/lib/python3.9/site-packages/pylast/__init__.py", line 571, in scrobble
    return self.scrobble_many(
  File "/home/ryan/.local/share/virtualenvs/cambot-Cr-HoN4d/lib/python3.9/site-packages/pylast/__init__.py", line 633, in scrobble_many
    _Request(self, "track.scrobble", params).execute()
  File "/home/ryan/.local/share/virtualenvs/cambot-Cr-HoN4d/lib/python3.9/site-packages/pylast/__init__.py", line 973, in execute
    response = self._download_response()
  File "/home/ryan/.local/share/virtualenvs/cambot-Cr-HoN4d/lib/python3.9/site-packages/pylast/__init__.py", line 962, in _download_response
    self._check_response_for_errors(response_text)
  File "/home/ryan/.local/share/virtualenvs/cambot-Cr-HoN4d/lib/python3.9/site-packages/pylast/__init__.py", line 983, in _check_response_for_errors
    raise MalformedResponseError(self.network, e) from e
pylast.MalformedResponseError: Malformed response from Last.fm. Underlying error: syntax error: line 1, column 0
```

I've been using pylast for a few years now but have never tried to manually scrobble anything before so wondered if I might have set it up wrong. Tried to scrobble an individual hardcoded track too and the same error.

**Comment by hugovk** [comment]
Thanks for checking. I'm scrobbling a lot with this script and it's still working with 4.3.0:
 https://github.com/hugovk/bbcscrobbler/blob/a5bfc093680731cc1167ef30057083e3451e55d1/bbcscrobbler.py#L178-L180

Here's a shorter script:

https://github.com/hugovk/lastfm-tools/blob/master/scrobble.py

I just tested that and it worked, for example:

```
python3 scrobble.py artist - songtitle
```

Maybe you can try this and then compare with your code?

Remember, for write operations you need to authenticate: https://github.com/pylast/pylast#getting-started

You can also enable pylast logging in case it gives something useful: https://github.com/pylast/pylast#logging

Something else to try, edit this bit of pylast code and print out the `response` before it tries to parse it, it may give a useful error:

https://github.com/pylast/pylast/blob/3db88e98ce77bc86bf533389b06a028a75251409/src/pylast/__init__.py#L977-L983

**Comment by ryancambray** [comment]
> Remember, for write operations you need to authenticate: https://github.com/pylast/pylast#getting-started

Hmm, turns out it was just this. I was not authenticating fully with the password in the setup. Removed this ages ago as I didn't need it. Came back to bite me!

Thanks for the help, this is happily scrobbling away now. All the best
