### ISSUE TITLE
Error when getting mbid of an album

### ISSUE THREAD

**Issue by inktrap** [pylast/pylast#389]
### What did you do?

If I get the album like this, it seems to work:

```pycon
>>> album = lastfm.get_album(artist="Various Artists", title="I Love Balkan Music")
>>> album
pylast.Album('Various Artists', 'I Love Balkan Music', pylast.LastFMNetwork('REDACTED', '', '', '', ''))
```

But if I want to access the `mbid`, it fails:

```pycon
>>> album.get_mbid()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "REDACTED/.direnv/python-3.9.10/lib/python3.9/site-packages/pylast/__init__.py", line 1633, in get_mbid
    return mbid.firstChild.nodeValue
AttributeError: 'NoneType' object has no attribute 'nodeValue'

'NoneType' object has no attribute 'nodeValue'
```

It should return `None` if there is no imdb-id, right?

### What versions are you using?

* Python: 3.9.10
* pylast: 4.5.0

**Comment by hugovk** [comment]
> It should return `None` if there is no imdb-id, right?

Yes, that sounds sensible.

Would you like to try PR https://github.com/pylast/pylast/pull/390?

**Comment by inktrap** [comment]
Yes, that branch works for me:

```
>>> import pylast
>>> lastfm = pylast.LastFMNetwork(api_key="REDACTED")
>>> album = lastfm.get_album(artist="Various Artists", title="I Love Balkan Music")
>>> print(album.get_mbid())
None
>>> album
pylast.Album('Various Artists', 'I Love Balkan Music', pylast.LastFMNetwork('REDACTED', '', '', '', ''))
```
