### ISSUE TITLE
Can't Love track using example code

### ISSUE THREAD

**Issue by bonelifer** [pylast/pylast#407]
### What did you do?
Tried using the example from the readme, to love a trrack.

### What did you expect to happen?
Love specified track

### What actually happened?
Some sort of authentication error.

### What versions are you using?

* OS: Xubuntu 20.04.4
* Python: 3.8
* pylast: most recent from Ubuntu package manager/pip3

Please include **code** that reproduces the issue.
Code in the Github readme

```
Traceback (most recent call last):
  File "last.py", line 11, in <module>
    network = pylast.LastFMNetwork(
  File "/home/william/.local/lib/python3.8/site-packages/pylast/__init__.py", line 670, in __init__
    super().__init__(
  File "/home/william/.local/lib/python3.8/site-packages/pylast/__init__.py", line 216, in __init__
    self.session_key = sk_gen.get_session_key(self.username, self.password_hash)
  File "/home/william/.local/lib/python3.8/site-packages/pylast/__init__.py", line 1072, in get_session_key
    doc = request.execute()
  File "/home/william/.local/lib/python3.8/site-packages/pylast/__init__.py", line 947, in execute
    response = self._download_response()
  File "/home/william/.local/lib/python3.8/site-packages/pylast/__init__.py", line 936, in _download_response
    self._check_response_for_errors(response_text)
  File "/home/william/.local/lib/python3.8/site-packages/pylast/__init__.py", line 965, in _check_response_for_errors
    raise WSError(self.network, status, details)
pylast.WSError: Authentication Failed - You do not have permissions to access the service

```

**Comment by hugovk** [comment]
It's failing to authenticate before even calling `track.love`, when creating the `network` object:

```python
network = pylast.LastFMNetwork(
    api_key=API_KEY,
    api_secret=API_SECRET,
    username=username,
    password_hash=password_hash,
)
```

I can reproduce.

Maybe Last.fm have removed that authentication method?

Instead of that line, can you try this lot instead?

```python
SESSION_KEY_FILE = os.path.join(os.path.expanduser("~"), ".session_key")
network = pylast.LastFMNetwork(API_KEY, API_SECRET)
if not os.path.exists(SESSION_KEY_FILE):
    skg = pylast.SessionKeyGenerator(network)
    url = skg.get_web_auth_url()

    print(f"Please authorize this script to access your account: {url}\n")
    import time
    import webbrowser

    webbrowser.open(url)

    while True:
        try:
            session_key = skg.get_web_auth_session_key(url)
            with open(SESSION_KEY_FILE, "w") as f:
                f.write(session_key)
            break
        except pylast.WSError:
            time.sleep(1)
else:
    session_key = open(SESSION_KEY_FILE).read()

network.session_key = session_key
```

Remember to call the `track.love` stuff afterwards:

```python
# Now you can use that object everywhere
track = network.get_track("Iron Maiden", "The Nomad")
track.love()
track.add_tags(("awesome", "favorite"))
```

**Comment by bonelifer** [comment]
Thanks. That worked. Now off to love my scrobbles. Scrobble scrobble.

**Comment by hugovk** [comment]
Good to hear!

Maybe related to https://github.com/pylast/pylast/issues/357.

Let's update the `README` to use this web authentication instead of username and password authentication. It's probably worth adding a helper function to pylast with the above snippet.

**Comment by bonelifer** [comment]
Not a programmer, so shooting in the dark, blind as hell. What do I do to  make this work? I'm more of a bash type of person.  I need to get the answer from those two mpc commands, so that I can pass it to the command below it.
```
artist = os.system("mpc -f %albumartist%")
title = os.system("mpc -f %title%")

# Now you can use that object everywhere
track = network.get_track(artist, title)
```
