### ISSUE TITLE
"Invalid parameters" when calling `artist.get_bio_content()`

### ISSUE THREAD

**Issue by mymindwentblvnk** [pylast/pylast#415]
### What did you do?
I asked for the bio from Journey.

### What did you expect to happen?
I wanted to get the bio from Journey.

### What actually happened?
I did get an error: `pylast.WSError: Invalid parameters - Your request is missing a required parameter`

```
Traceback (most recent call last):
  File "/Users/michael/Library/Application Support/JetBrains/PyCharm2022.1/scratches/scratch.py", line 13, in <module>
    print(artist.get_bio_content())
  File "/Users/michael/workspace/topic-modelling-workshop/venv/lib/python3.10/site-packages/pylast/__init__.py", line 1792, in get_bio_content
    return self.get_bio("content", language)
  File "/Users/michael/workspace/topic-modelling-workshop/venv/lib/python3.10/site-packages/pylast/__init__.py", line 1774, in get_bio
    bio = self._extract_cdata_from_request(
  File "/Users/michael/workspace/topic-modelling-workshop/venv/lib/python3.10/site-packages/pylast/__init__.py", line 1129, in _extract_cdata_from_request
    doc = self._request(method_name, True, params)
  File "/Users/michael/workspace/topic-modelling-workshop/venv/lib/python3.10/site-packages/pylast/__init__.py", line 1112, in _request
    return _Request(self.network, method_name, params).execute(cacheable)
  File "/Users/michael/workspace/topic-modelling-workshop/venv/lib/python3.10/site-packages/pylast/__init__.py", line 947, in execute
    response = self._download_response()
  File "/Users/michael/workspace/topic-modelling-workshop/venv/lib/python3.10/site-packages/pylast/__init__.py", line 936, in _download_response
    self._check_response_for_errors(response_text)
  File "/Users/michael/workspace/topic-modelling-workshop/venv/lib/python3.10/site-packages/pylast/__init__.py", line 965, in _check_response_for_errors
    raise WSError(self.network, status, details)
pylast.WSError: Invalid parameters - Your request is missing a required parameter
```

### What versions are you using?

* OS: 12.6
* Python: 3.10
* pylast: 5.0.0

```python
import pylast
import os


network = pylast.LastFMNetwork(
    api_key=os.getenv('API_KEY'),
    api_secret=os.getenv('API_SECRET'),
    username=os.getenv('USER'),
    password_hash=pylast.md5(os.getenv('PASSWORD'))
)

artist = network.get_artist('Journey')
print(artist.get_bio_content())
```

**Comment by mymindwentblvnk** [comment]
Same for `network.get_authenticated_user().get_country()` and other calls.

**Comment by mymindwentblvnk** [comment]
Looks like my `.env` was not loaded correctly. Error message was misleading. Sorry for the noise 👋
