### ISSUE TITLE
IndexError in `get_recent_tracks` when `now_playing=True`

### ISSUE THREAD

**Issue by ndm13** [pylast/pylast#422]
### What did you do?
Called `get_recent_tracks` on the current `pylast` user, with `now_playing` set to `True` and a track currently playing.

### What did you expect to happen?
The returned history should include the requested number of tracks, including the currently playing one at the top.

### What actually happened?
Received `IndexError: list index out of range` in `_extract_played_track` line 2211.

### What versions are you using?

* OS: Windows 10 x64
* Python: 3.10
* pylast: 5.1.0

Please include **code** that reproduces the issue.

```python
import pylast

last = pylast.LastFMNetwork(API_KEY, API_SECRET, USER_TOKEN, USER_NAME)
for track in last.get_authenticated_user().get_recent_tracks(now_playing=True):
    print(track)
```

```pytb
Traceback (most recent call last):
  File "X:\project-root\scratch.py", line 9, in <module>
    for track in last.get_authenticated_user().get_recent_tracks(now_playing=True):
  File "X:\project-root\venv\lib\site-packages\pylast\__init__.py", line 2359, in get_recent_tracks
    return _get_recent_tracks() if stream else list(_get_recent_tracks())
  File "X:\project-root\venv\lib\site-packages\pylast\__init__.py", line 2356, in _get_recent_tracks
    yield self._extract_played_track(track_node=track_node)
  File "X:\project-root\venv\lib\site-packages\pylast\__init__.py", line 2211, in _extract_played_track
    timestamp = track_node.getElementsByTagName("date")[0].getAttribute("uts")
IndexError: list index out of range
```

Note that the code behaves as expected when `now_playing=False` or when the user is not currently playing something.  I searched the issues and found #33 which seems to match this, but it's a very old issue.

**Comment by ndm13** [comment]
My current workaround is to fetch the now playing independently and add it manually.

```python
now_playing = last.get_authenticated_user().get_now_playing()
history = [now_playing] if now_playing is not None else []
history.extend(map(lambda e: e.track, last.get_authenticated_user().get_recent_tracks(stream=True)))

for track in history:
    print(track)
```

**Comment by hugovk** [comment]
This looks like a Last.fm bug.

It's falling over on `timestamp = track_node.getElementsByTagName("date")[0].getAttribute("uts")`:

```python
    def _extract_played_track(self, track_node):
        title = _extract(track_node, "name")
        print(title)
        track_artist = _extract(track_node, "artist")
        date = _extract(track_node, "date")
        album = _extract(track_node, "album")
        timestamp = track_node.getElementsByTagName("date")[0].getAttribute("uts")
        return PlayedTrack(
            Track(track_artist, title, self.network), album, date, timestamp
        )
```

Because there is no "date" element for the now playing track.

For example, looking at the API response for https://www.last.fm/user/bbc6music's nowplaying:

https://ws.audioscrobbler.com/2.0/?method=user.getrecenttracks&user=bbc6music&api_key=TODO

```xml
<lfm status="ok">
  <recenttracks user="bbc6music" page="1" perPage="50" totalPages="28322" total="1416084">
    <track nowplaying="true">
      <artist mbid="b614843c-bec3-421f-9af1-03169cdd4b63">Quasimoto</artist>
      <name>Come On Feet</name>
      <streamable>0</streamable>
      <mbid>066c08c8-4c1c-4770-8d59-41bdd365fe64</mbid>
      <album mbid=""/>
      <url>https://www.last.fm/music/Quasimoto/_/Come+On+Feet</url>
      <image size="small"/>
      <image size="medium"/>
      <image size="large"/>
      <image size="extralarge"/>
    </track>
    <track>
      <artist mbid="b614843c-bec3-421f-9af1-03169cdd4b63">Quasimoto</artist>
      <name>Come On Feet</name>
      <streamable>0</streamable>
      <mbid>066c08c8-4c1c-4770-8d59-41bdd365fe64</mbid>
      <album mbid=""/>
      <url>https://www.last.fm/music/Quasimoto/_/Come+On+Feet</url>
      <image size="small"/>
      <image size="medium"/>
      <image size="large"/>
      <image size="extralarge"/>
      <date uts="1673005448">06 Jan 2023, 11:44</date>
    </track>
    <track>
      <artist mbid="">Nate Brazier</artist>
      <name>Patterns</name>
      <streamable>0</streamable>
      <mbid/>
      <album mbid=""/>
      <url>https://www.last.fm/music/Nate+Brazier/_/Patterns</url>
      <image size="small"/>
      <image size="medium"/>
      <image size="large"/>
      <image size="extralarge"/>
      <date uts="1673005249">06 Jan 2023, 11:40</date>
    </track>
```

That first track is the now playing one: `<track nowplaying="true">`

But it has no `<date ...>`.

The others, which are scrobbled tracks, do:

```xml
<date uts="1673005448">06 Jan 2023, 11:44</date>
...
<date uts="1673005249">06 Jan 2023, 11:40</date>
```

This looks like a bug on the Last.fm side.

And the API documentation page for [`user.getRecentTracks`](https://www.last.fm/api/show/user.getRecentTracks) does show a `<date>` for the `nowplaying` track:

```xml
<recenttracks user="RJ" page="1" perPage="10" totalPages="3019">
  <track nowplaying="true">
    <artist mbid="2f9ecbed-27be-40e6-abca-6de49d50299e">Aretha Franklin</artist>
    <name>Sisters Are Doing It For Themselves</name>
    <mbid/>
    <album mbid=""/>
    <url>www.last.fm/music/Aretha+Franklin/_/Sisters+Are+Doing+It+For+Themselves</url>
    <date uts="1213031819">9 Jun 2008, 17:16</date>
    <streamable>1</streamable>
  </track>
  ...
</recenttracks>
```

I've reported it to Last.fm: https://support.last.fm/t/regression-date-missing-from-nowplaying-in-user-getrecenttracks/69875?u=hvk
