### ISSUE TITLE
Can't pull top track data?

### ISSUE THREAD

**Issue by submeg** [pylast/pylast#429]
### What did you do?
Tried to use get_top_tracks to pull the user's most played tracks, used the recent tracks idea as an example.

### What did you expect to happen?
A print out of the track name, play count and loved status.

### What actually happened?
Code didn't complete, stuck on trying to obtain data

### What versions are you using?

* OS: Windows 10 Pro
* Python: 3.10
* pylast: 5.1.10

Please include **code** that reproduces the issue.

The [best reproductions](https://stackoverflow.com/help/minimal-reproducible-example)
are
[self-contained scripts](https://ericlippert.com/2014/03/05/how-to-debug-small-programs/)
with minimal dependencies.

```python

import pylast

#=======================================================================================

def main():

    API_KEY = "KEY"
    API_SECRET = "SECRET"

    # In order to perform a write operation you need to authenticate yourself
    username = "USER"
    password_hash = pylast.md5("PASS")

    network = pylast.LastFMNetwork(
        api_key=API_KEY,
        api_secret=API_SECRET,
        username=username,
        password_hash=password_hash,
    )

    print("\nHELLO\n\n")

    user = network.get_user(username)
    print('Correctly gets user: ' + str(user))

    # ----------------------------------------------------
    print("--------------")

    # print("Recent Tracks: (All should be played at least once)")
    #
    # for pt in user.get_recent_tracks():
    #     t = pt.track
    #     print(t, "\n", "play count: ", t.get_userplaycount(), "   Loved? ", t.get_userloved())

    print("------------------------------------------------------------")

    print("Top tracks:")

    for pt in user.get_top_tracks():
        t = pt.track
        print(t, "\n", "play count: ", t.get_userplaycount(), "   Loved? ", t.get_userloved())

    #-------------------------------------------------------------

```

**Comment by hugovk** [comment]
Which line does it get stuck on? Does it output any data before getting stuck? Does it get stuck in the same place every time?

**Comment by submeg** [comment]
it outputs the following:

HELLO


Correctly gets user: Submeg
--------------
------------------------------------------------------------

Traceback (most recent call last):
  File "D:\Users\LOCALUser\PycharmProjects\Music8Ball\Main.py", line 101, in <module>
    main()
  File "D:\Users\LOCALUser\PycharmProjects\Music8Ball\Main.py", line 50, in main
    t = pt.track
AttributeError: 'TopItem' object has no attribute 'track'

Process finished with exit code 1

**Comment by hugovk** [comment]
`user.get_top_tracks` returns `TopItem`s, which don't have a `track`, and look like:

```python
TopItem(item=pylast.Track('Elastica', 'Waking Up', pylast.LastFMNetwork(...)), weight=378)
```

To fix, replace `pt.track` with `pt.item`.
