### ISSUE TITLE
pylast.MalformedResponseError: Malformed response from Last.fm. Underlying error: syntax error: line 1, column 0 when Network.scrobble method is called

### ISSUE THREAD

**Issue by hypogirl** [pylast/pylast#459]
### What did you do?
I tried scrobbling a track by calling the scrobble method.

### What did you expect to happen?
I was expecting the track to scrobble.

### What actually happened?
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pylast/__init__.py", line 962, in _check_response_for_errors
    doc = minidom.parseString(_string(response).replace("opensearch:", ""))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xml/dom/minidom.py", line 2000, in parseString
    return expatbuilder.parseString(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xml/dom/expatbuilder.py", line 925, in parseString
    return builder.parseString(string)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/xml/dom/expatbuilder.py", line 223, in parseString
    parser.Parse(string, True)
xml.parsers.expat.ExpatError: syntax error: line 1, column 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hypogirl333/Desktop/scrobbler.py", line 21, in <module>
    network.scrobble(artist= artist, title= title, album= album, timestamp= int(timestamp))
  File "/usr/lib/python3/dist-packages/pylast/__init__.py", line 569, in scrobble
    return self.scrobble_many(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pylast/__init__.py", line 631, in scrobble_many
    _Request(self, "track.scrobble", params).execute()
  File "/usr/lib/python3/dist-packages/pylast/__init__.py", line 954, in execute
    response = self._download_response()
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/pylast/__init__.py", line 943, in _download_response
    self._check_response_for_errors(response_text)
  File "/usr/lib/python3/dist-packages/pylast/__init__.py", line 964, in _check_response_for_errors
    raise MalformedResponseError(self.network, e)
pylast.MalformedResponseError: Malformed response from Last.fm. Underlying error: syntax error: line 1, column 0

### What versions are you using?

* OS: ChromeOS
* Python: 3.11.2
* pylast: pylast-5.3.1.dev3

Please include **code** that reproduces the issue.

The [best reproductions](https://stackoverflow.com/help/minimal-reproducible-example)
are
[self-contained scripts](https://ericlippert.com/2014/03/05/how-to-debug-small-programs/)
with minimal dependencies.

```python
while artist:=input("artist: ") != "qwerty123":
    album = input("album: ")
    timestamp = epoch_time(datetime.strptime(input("dd mm yyyy hh mm ss: "), "%d %m %Y %H %M %S"))
    
    while title:= input("title: ") != "qwerty123":
        
        try:
            duration = int(input("duration: "))
        except:
            duration = 60*4

        print(timestamp)
        network.scrobble(artist= artist, title= title, album= album, timestamp= int(timestamp))
        timestamp += duration
```

**Comment by csazevedo** [comment]
Can you share the full example? I ran into the same issue and the problem was how I was creating your `network` object.
