### ISSUE TITLE
test_unscrobble sometimes fails on my machine

### ISSUE THREAD

**Issue by hugovk** [pylast/pylast#89]
`test_unscrobble` sometimes fails on my machine (using Python 2.7) but passes on CI (2.7 and 3.3). 

Fix it.

```
$ ./test_pylast.py
......................................................................................E.............
....
======================================================================
ERROR: test_unscrobble (__main__.TestPyLast)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./test_pylast.py", line 77, in test_unscrobble
    artist=artist, title=title, timestamp=timestamp)
  File "c:\Users\hugovk\github\pylast\pylast.py", line 2648, in remove_scrobble
    self._request(self.ws_prefix + ".removeScrobble", False, params)
  File "c:\Users\hugovk\github\pylast\pylast.py", line 1321, in _request
    return _Request(self.network, method_name, params).execute(cacheable)
  File "c:\Users\hugovk\github\pylast\pylast.py", line 1149, in execute
    response = self._download_response()
  File "c:\Users\hugovk\github\pylast\pylast.py", line 1140, in _download_response
    self._check_response_for_errors(response_text)
  File "c:\Users\hugovk\github\pylast\pylast.py", line 1167, in _check_response_for_errors
    raise WSError(self.network, status, details)
WSError: Invalid timestamp

----------------------------------------------------------------------
Ran 104 tests in 229.699s

FAILED (errors=1)
```

**Comment by hugovk** [comment]
Not seen this for a while.
